#!/usr/bin/python
alias_exists         = 'Alias already exists!';
disk_activated       = 'Disk activated.';
disk_activate_failed = 'Can not activate disk!';
share_exists         = 'Share exists! Create failed.';
con_success          = 'Connection successful.';
con_failed           = 'Connection failed!';
values_changed       = 'Values updated.';
create_nas_disk      = 'Please create a NAS disk to create a share.';
no_shares_present    = 'No shares present!';
service_restarted    = 'Service(s) restarted.';
service_failed       = 'Could not restart the service!';
disk_deleted         = 'Disk deleted!';
disk_in_use          = 'Disk in use! Delete failed!';
share_deleted        = 'Share deleted!';
service_started      = 'Service started!';
service_not_started  = 'Could not start the service!';
service_stopped      = 'Stopped the service.';
volume_removed       = 'Volume removed!';
invalid_date         = 'Invalid date!';
date_changed         = 'Date changed.';
volume_created       = 'Volume created.';
volume_failed        = 'Failed to create volume!';
alias_removed        = 'Alias removed!';
disk_deactivated     = 'Disk de-activated!';
space_exhausted      = 'Out of space. Cannot create volume';
snapshot_created     = 'Snapshot created.';
snapshot_failed      = 'Failed to create snapshot!';
valid_user_pwd       = 'Please enter a valid username and password!';
snapshot_deleted     = 'Snapshot deleted!';
delete_failed        = 'Delete failed!';
scheduled_for_backup = 'Scheduled for backup';
backup_success       = 'Data backup successful!';
vtls_enabled         = 'VTLS Configuration done!';
vtls_disabled        = 'Disabled VTLS!';
page_access_error    = 'Error accessing page!';
login_again_message  = 'Please login again!';
